### PR TITLE
fixed the backspace issue

### LINKED ISSUE #2: Odd behavior with backspace
I'm noticing odd behavior with the Backspace button when I press it multiple times.

**To Reproduce**
1. Start a new game
2. Enter a letter like "Q"
3. Hit backspace 3 times
4. Now hit "Q" again
5. You'll see that the letter does not appear on the board.
6. You have to press "Q" two more times for it to appear on the board.

**Expected Behavior:**
1. Enter "Q"
2. Press backspace 3 times
3. Press "Q" again
4. "Q" immediately appears in the first tile

### PR DESCRIPTION
**Pull request by Vai-Sur05**
Closes  #2

### CODE REVIEW

File: resources/js/Store/index.js [hunk 1]
```diff
@@ -90,15 +93,24 @@ export default createStore({
     },
     actions: {
         submitCharacter({ state, commit, getters }, char) {
-            if(getters.allCharsEntered) {
-                return // don't accept more characters after all have been entered
+            if (getters.allCharsEntered || state.gameGrid[state.rowIndex][state.charIndex] !== '') {
```
Comment (bbeng89) [inline resources/js/Store/index.js:96]: Good catch here! Can you refactor this logic `state.gameGrid[state.rowIndex][state.charIndex]` into a getter method? This will make the code more readable and make this logic reusable.

**Review by bbeng89 — CHANGES_REQUESTED** [review]
Good work! Aside from the one requested change, can you drop all the debugging messages (console.log) and remove the semicolons, just for code style consistency?
